services:
  - type: web
    name: backend-dep
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,backend-dep.onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: FRONTEND_URL
        value: https://dep-party.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://dep-party.onrender.com,https://dep-party.com 