services:
  - type: web
    name: backend-dep-kwln
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: backend-dep-kwln.onrender.com
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1 