# Generated by Django 5.2.1 on 2025-05-13 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_gallery_media_type_gallery_thumbnail_gallery_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalleadership',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nationalleadership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
