# Generated by Django 5.2.1 on 2025-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_remove_membership_end_date_remove_membership_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_modifier_type',
            field=models.CharField(choices=[('none', 'None'), ('multiply', 'Multiply'), ('add', 'Add')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='price_modifier_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value to multiply or add to the base price', max_digits=10),
        ),
    ]
