# Generated by Django 5.2.1 on 2026-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0014_gallery_video_cloudinary_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
    ]
